import Header from "@/components/header/Header";
import ScrollProgressBar from "@/components/ScrollProgressBar/ScrollProgressBar";
import type { Metadata } from "next";
import { Syne } from 'next/font/google'
import "./globals.css";


export const metadata: Metadata = {
  title: "dataclaps",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const syne = Syne({
  weight: ['400','700'],
  subsets: ['latin'],
})
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={syne.className}>
        <Header/>
        <ScrollProgressBar />
        {children}
      </body>
    </html>
  );
}
